// ==UserScript==
// @name Blockhead
// @namespace blockhead
// @description Blocks headers and other sticky elements from wasting precious vertical screen estate by pinning them down.
// @match *://*/*
// @version     2
// @grant none
// @author elypter
// @downloadURL https://raw.githubusercontent.com/elypter/BlockHead/master/blockhead.user.js
// @updateURL https://raw.githubusercontent.com/elypter/BlockHead/master/blockhead.user.js
// ==/UserScript==

//This script blocks headers and other sticky elements from wasting precious vertical screen estate by pinning them down.
//It checks the computed style of each element. if the position attribute is relative, fixed or absolute
//then it checks if its id or classes names contain provided in the list below.
//this list is created with theis tool https://github.com/elypter/rule_keyword_generator by parsing the rules https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt
//for class names and ids.
//There is also a whitelist for certain keywords and tag names to reduce flase positives and processing time.
//currently the processing time is quite high because each element has to be checked and many have to be checked against the whole list.
//on an old laptop it can take up to single digit seconds so pageloadtime noticable increases.

var black_keywords=["site",
"inline",
"js",
"bx",
"social",
"navbar",
"header",
"share",
"story",
"ui",
"td",
"nav",
"sticky",
"pluto",
"ad",
"article",
"sd",
"footer",
"main",
"fixed",
"is",
"utility",
"android",
"newsletter",
"top",
"fa",
"component",
"front",
"block",
"jw",
"mobile",
"__pw",
"col",
"metabar",
"clearfix",
"overlay",
"smart",
"hidden",
"first",
"smp",
"gallery",
"gig",
"headroom",
"pb",
"menu",
"post",
"content",
"mod",
"icon",
"modal",
"btn",
"button",
"masthead",
"back",
"onesignal",
"page",
"no",
"twitter",
"visible",
"show",
"scroll",
"fb",
"module",
"global",
"hide",
"vjs",
"tmblr",
"ubermenu",
"container",
"widget",
"smallarticleattophtml5",
"sidebar",
"facebook",
"priority",
"arrows",
"playlistsmallattophtml5",
"fb_recommend",
"pane",
"pw",
"slide",
"mobileweb",
"dfp",
"email",
"adi",
"cookie",
"cc",
"in",
"text",
"entry",
"fancybox",
"js_post",
"mashsb",
"navigation",
"bottom",
"subscribe",
"cb",
"cns",
"nytc",
"nav__social",
"follow",
"tab",
"xs",
"asset",
"mm",
"pum",
"ssbp",
"ng",
"has",
"sharing",
"row",
"leaderboard",
"region",
"g1",
"amp",
"primary",
"sharedaddy",
"field",
"banner",
"app",
"cd",
"responsive",
"fusion",
"right",
"floating",
"small",
"section",
"bg",
"js_newsletter",
"position",
"search",
"action",
"cm",
"js_ad",
"flex",
"sub",
"video",
"active",
"swiper",
"scale",
"shareaholic",
"echo",
"panel",
"bb",
"left",
"mh",
"tve",
"to",
"desktop",
"slim",
"item",
"sdc",
"layout",
"iframe",
"adsbygoogle",
"list",
"large",
"mfp",
"mvp",
"js_subscribe",
"pushcrew",
"publication",
"pull",
"popover",
"topbar",
"fade",
"uni",
"spu",
"blog",
"next",
"subscription",
"wf",
"hamburger",
"full",
"sun",
"popup",
"wrapper",
"d1",
"not",
"vertical",
"single",
"float",
"stuck",
"horizontal",
"Post",
"uvn",
"space",
"logo",
"sharebar",
"secondary",
"mega",
"signup",
"style__mast",
"ks",
"cta",
"remodal",
"rj",
"cfat",
"yui3",
"advertisement",
"is_stuck",
"longform",
"clear",
"border",
"new",
"fly",
"image",
"sign",
"affix",
"vf",
"Header",
"dd",
"et",
"svgIcon",
"jetpack",
"akamai",
"meta",
"standard",
"msg",
"sw",
"st",
"card",
"city",
"lia",
"lf",
"contextual",
"ss",
"ra1",
"style__wsj",
"smartbanner",
"column",
"featured",
"rrssb",
"boxzilla",
"stick",
"embed",
"fl",
"ara",
"alert",
"fyre",
"mdl",
"sqs",
"user",
"contain",
"actionbar",
"promo",
"hp",
"margin",
"pad",
"dfp_ad",
"mini",
"quick",
"mkdf",
"ribbon",
"box",
"up",
"go",
"cf",
"met",
"news",
"toolbar",
"prev",
"reveal",
"nc",
"with",
"meter",
"dynamic",
"synved",
"mk",
"mailmunch",
"head",
"progress",
"default",
"recirc",
"pinned",
"google",
"style__stick",
"link",
"edition",
"style__scrolled_2R_Vmp",
"side",
"d2",
"wp",
"background",
"WSJTheme__sector",
"mi",
"views",
"socialNetworks",
"atavist",
"wsj",
"buttonSet",
"stb",
"robots",
"move",
"related",
"skinny",
"devsite",
"webform",
"theme",
"sr",
"columns",
"art",
"lower",
"uk",
"Grid",
"body",
"pgevoke",
"WSJTheme__md",
"hero",
"cdev",
"feature",
"mf",
"ibm",
"sm",
"media",
"dark",
"tc",
"pinterest",
"rebelbar",
"scrolled",
"js_meta",
"yfa",
"nc_socialPanel",
"ember",
"v2",
"mx",
"adblock",
"tout",
"badge",
"color",
"read",
"om",
"fs",
"center",
"stack",
"static",
"scrolling",
"home",
"offset",
"powa",
"ra",
"bar",
"sharetools",
"title",
"fb_iframe_widget",
"tl",
"style",
"connect",
"gpt",
"addthis_toolbox",
"toggle",
"rdm",
"cc_container",
"injected",
"cne",
"cnn",
"group",
"cbs",
"r1f",
"tw",
"align",
"print",
"nbcsports",
"swp_d_fullColor",
"catapult",
"animated",
"popmake",
"sharingfooter",
"grid",
"eltd",
"dpsp",
"closed",
"ArticlePagerItem",
"fit",
"network",
"tgc",
"el__leafmedia",
"adhesionUnit",
"rail",
"soc",
"can",
"snp",
"message",
"open",
"size",
"rmq",
"ddb",
"ksat",
"simple",
"postActions",
"bn",
"code",
"gh",
"taboola",
"breaker",
"inner",
"persistent",
"rh",
"adAdhesionSidebar",
"take",
"adv_network",
"social_21069380",
"get",
"on",
"tm",
"adv_header",
"swp_i_fullColor",
"onstoq",
"macdongle",
"recent",
"info",
"adTower",
"collection",
"privacy",
"comment",
"article__share",
"vw",
"itbelwjba",
"logged",
"adv_mobi_edition",
"warning_empty_div",
"mc",
"ms",
"uproxx",
"util",
"apss",
"siBar",
"socialIcons",
"BlockAdvert",
"dy",
"swp_flatFresh",
"animate",
"marketing",
"highlightMenu",
"icon16",
"brand",
"pure",
"sb",
"sa",
"ec",
"mrt",
"reading",
"mol",
"o2",
"ts",
"stickynav",
"moat",
"instream",
"wnad",
"chorus",
"leadinModal",
"actnbr",
"Mobile",
"proper",
"jumpstart",
"nyp",
"articles",
"stickyNav",
"display",
"addthis_default_style",
"Block",
"mailchimp",
"frieze",
"topcontrol",
"tooltipster",
"df",
"wbtz",
"super",
"wrap",
"width",
"medium",
"topic",
"aol",
"sc",
"mc_embed_signup",
"white",
"socialite",
"yt",
"Logo",
"as",
"instagram",
"flag",
"socials",
"yv",
"ProfileCanopy",
"cover",
"wpsr",
"close",
"pt",
"voc",
"br",
"collapsed",
"highlight",
"smaller",
"light",
"special",
"generic",
"sharerich",
"socialIcon",
"trb_nh",
"fix",
"wpfront",
"kiwi",
"swp_o_fullColor",
"share__social",
"socialShare",
"rune",
"nocontent",
"the",
"save",
"shadow",
"topnav",
"site__priNav",
"notification",
"unit",
"wwd",
"template",
"shared",
"sg",
"adhesive",
"lede",
"teads",
"aside",
"recipe",
"review",
"hdr",
"markup",
"justify",
"photos",
"mast",
"floater",
"breaking",
"fc",
"mt",
"addtoany_share_save_container",
"font",
"__hub",
"custom",
"sde",
"ess",
"js_dismissable",
"auto",
"ksl",
"lb",
"mainmenu",
"hc",
"fullwidth",
"blue",
"join",
"kicker",
"md",
"sharrre",
"parbase",
"tnt",
"wwe",
"spnf_ticker",
"colorbox",
"gridlove",
"return",
"cnbc",
"youtube",
"backtotop",
"condensed",
"shunno",
"dongle",
"scrollToTop",
"dropdown",
"meta__tools",
"FP",
"thm",
"stock",
"cboxOverlay",
"attach",
"slider",
"zergnet",
"cs",
"vp",
"partner",
"infinite",
"adr",
"pin",
"trb_gptAd",
"feedback",
"trb_mh_adB",
"mt3_row",
"atb",
"regular",
"AppBanner",
"il",
"contact",
"adspot",
"WNNavSearchSwitch",
"navstory__arrow",
"promos",
"_3f2NsD",
"node",
"pullquote",
"comments",
"essbfc",
"upper",
"current",
"optinform",
"privy",
"post__article",
"story__links",
"graf",
"one",
"ssk",
"dc_morning_email",
"shift",
"th",
"homepage",
"linkedin",
"csn",
"jwloader",
"fe",
"fk",
"cc_banner",
"spnf_right",
"snope",
"subnav",
"react",
"add",
"swp_one",
"seo",
"tabcontent",
"expanded",
"wx",
"StickyHeadline",
"bp",
"fixedsticky",
"recommended",
"originals",
"a2a_kit",
"opinion",
"heavy_ad",
"introjs",
"reg",
"navbar__item",
"qa",
"view",
"off",
"trb_masthead_adBanner",
"hnst",
"sibling",
"fixie",
"nextgen",
"highlights",
"pbs",
"asset_balaNotification",
"fe_banner__w",
"preloaded_lightbox",
"YDC",
"callout",
"toTop",
"best",
"frb",
"googleplus",
"chapter",
"beta",
"nl",
"glyphicon",
"mb",
"telegraf",
"ipu",
"page_header",
"stream",
"divider",
"mail",
"jsid",
"circa",
"huc",
"page__header",
"author",
"events",
"exit",
"two",
"more",
"thega",
"prompt",
"ftr",
"rtli",
"guest",
"et_social_animated",
"ssba",
"last",
"shortcode",
"match",
"widget_text",
"header__inner",
"tablet",
"fb_digioh",
"step",
"bq",
"bs",
"_2JO",
"js_top",
"ga",
"et_social_mobile_on",
"cttus",
"w14",
"armonioso",
"AppBar",
"min",
"ctpl",
"frame",
"wc",
"zgt",
"opt360",
"adb",
"UH",
"lsi",
"spev",
"locked",
"end",
"headhesive",
"arrow",
"style__scrolled_1KqqY_CTh3JC3M",
"adhesion",
"js_global",
"mainNav",
"reserve",
"headline",
"hellobar",
"dc",
"header_1",
"paywall",
"nature",
"addtoany_content_bottom",
"loaded",
"footer__social",
"player",
"crt",
"ndn_toggleShare",
"boxes",
"swal2",
"hat",
"hst",
"support",
"paging",
"vuukle",
"trip",
"simplemodal",
"skrollable",
"welcome",
"zone",
"back_to_top",
"div",
"embed_code",
"flx",
"cat",
"IssueNav",
"so",
"csf",
"fw",
"a2a_kit_size_32",
"carousel",
"footer__column",
"cleared",
"entry__bottom",
"et_social_sidebar_networks",
"et_social_visible_sidebar",
"jp",
"site_ad",
"overview",
"gjs",
"clay",
"presentation",
"slick",
"No",
"coupon",
"transporter",
"styles__sector",
"fill",
"issuem",
"alt",
"dsq",
"postActionsBar",
"pico",
"fd",
"grey",
"sponsored",
"donate",
"pdp",
"adops",
"pd",
"ozy",
"ac",
"fdbst",
"prominent",
"big",
"NavFrame__below",
"dialog",
"ndn_icon_share",
"once",
"bxc",
"cnav",
"announce",
"dac",
"appIntercept",
"rsv",
"lin",
"tve_cta",
"trb_bnn",
"selection",
"styles__md",
"cp",
"bsa",
"RC",
"ap",
"tracked",
"tighten",
"essb_links_list",
"newsstand",
"keystone",
"stay",
"pn",
"advads",
"slideshow",
"siteNav",
"leaky",
"bank",
"ipc",
"cmg",
"series",
"wpsso",
"gradient",
"header_wrap",
"toc",
"centered",
"above",
"backToTop",
"scrolltofixed",
"advert",
"pro",
"dashboard",
"growl",
"rappler3",
"top_header",
"StickyNavbar",
"lightbox",
"scroll_header_top_area",
"form",
"shrink",
"daily",
"push",
"pmc",
"ArticlePage",
"controls",
"slideout",
"drawer",
"mc4wp",
"max",
"ad_container",
"blocker",
"maia",
"en",
"eu",
"a2a_floating_style",
"yui",
"bling",
"padding",
"nav__main",
"uiLayer",
"toprail",
"shop",
"ytd",
"hdnce",
"relative",
"comp",
"optIn",
"gray",
"yj",
"imoneza",
"trb_nls_c",
"stationary",
"shadowbox",
"oo",
"scrollup",
"article_0_ad_square",
"social_links",
"icons",
"sans",
"click_open",
"a2a_vertical_style",
"bundle",
"SimpleAd",
"pinit",
"ifancybox",
"riser",
"major",
"_3fN",
"swp_three",
"img",
"tertiary",
"shareMenu",
"facebookShare",
"szig",
"fullscreen",
"ads",
"FloatingOIA",
"headed",
"___plusone_0",
"docked",
"PopupSignupForm_0",
"sticky_header",
"marca",
"buttons",
"ActionButtonRow",
"Button",
"ba",
"bk",
"disclosure",
"uv",
"warning",
"chat",
"Ad",
"Newsletter",
"claudia",
"explore",
"from",
"links",
"sideSlide",
"byline",
"hive",
"wnad43",
"striped",
"gdongle",
"login",
"well",
"glue",
"auto_open",
"Hero",
"wprmenu_bar",
"count",
"lockfixed",
"breadcrumb"];

//id and classes that contain any of these keywords will not be modified
var white_names = ["side","article","video","story","main","left","right","content","panel"];

//tags that will not be cheked
var ignore_tags = ["a","A","script","SCRIPT","body","BODY","li","LI","ul","UL","br","BR","h5","H5","b","B","strong","STRONG","svg","SVG","path","PATHH","h2","H2",
                   "code","CODE","tr","TR","td","TD","h3","H3","h1","H1","h4","H4"];//,"noscript","NOSCRIPT"

var mutation_check=true; //search for floating elements that get added after page load.
var substring_search=true; //cannot be switched off anymore.

var counter=0;//debug:counts how often a page check is triggered
var generated_rules=[]; //contains all adblock/ublock rules that the script creates based on what it modifies

function c_walk(elm,orig){
    counter++;
    //console.log("check number "+counter+" from: "+orig);
    walk(elm);
}

function c_match(keyword_list){
    //todo: switch order of for loops to detect whitelists earlier
    var state=-1;
    //console.log("list: ("+keyword_list.length+") "+keyword_list)
    for (var i=0; i < keyword_list.length; i++){
        var subword_list=keyword_list[i].toString().split('-');
        //console.log("sublen of: "+subword_list+" from "+keyword_list[i]+" = "+subword_list.length);
        for (var j=0; j < subword_list.length; j++){
            var subsubword_list=subword_list[j].split('_');
            //console.log("subsublen of: "+subsubword_list+" from "+subword_list[j]+" = "+subsubword_list.length);
            for (var k=0; k < subsubword_list.length; k++){
                for (var l=0; l < white_names.length; l++){
                    //console.log("test white: l:"+white_names[l]+" in s:"+subsubword_list[k]+" of "+keyword_list);
                    if (subsubword_list[k].indexOf(white_names[l]) !== -1){
                        //console.log("whitelisted: l:"+white_names[l]+" in s:"+subsubword_list[k]+" of "+keyword_list);
                        return 0;
                    }
                }
                for (var m=0; m < black_keywords.length; m++){
                    if (subsubword_list[k].indexOf(black_keywords[m]) !== -1){
                        //console.log("matched: l:"+black_keywords[m]+" in s:"+subsubword_list[k]+" of "+keyword_list);
                        state = 1;
                    }
                }
            }
        }
    }
    //console.log("state: "+state+" of "+keyword_list);
    return state;
}

function walk(elm) {
    //if (elm instanceof Element) if (ignore_tags.indexOf(elm.tagName.toString()) > -1) return;
    var node;
    if(elm instanceof Element && ignore_tags.indexOf(elm.tagName.toString()) == -1 && getComputedStyle(elm)) {if ((getComputedStyle(elm).getPropertyValue("position") == "absolute") ||
                                    (getComputedStyle(elm).getPropertyValue("position") == "fixed") ||
                                    (getComputedStyle(elm).getPropertyValue("position") == "relative") ||
                                    (getComputedStyle(elm).getPropertyValue("top") != "")) {
        var keyword_list =[];
        keyword_list=elm.className.toString.toString().split(' ');
        if (typeof(elm.id)=="string"&&elm.id!="") keyword_list.push([elm.id]);

        var has_matched=-1;
        if (keyword_list!=[]&&keyword_list!=[""]){
            has_matched=c_match(keyword_list);
        }
        var rule;
        var class_list=elm.className.toString().split(' '); //check for rule writing
        if (has_matched==1){
            //console.log("pinning sticky: "+elm.id+","+elm.className+","+elm.tagName);

            if (elm.id){
                rule=window.location.hostname+"###"+elm.id+":style(position: "+"fixed"+" !important;)";
                if(generated_rules.indexOf(rule)==-1){
                    generated_rules.push(rule);
                    console.log(rule);
                }
            }
            if(elm.className){
                for (var i=0; i < class_list.length; i++){
                    rule=window.location.hostname+"##."+class_list[i]+":style(position: "+"fixed" +" !important;)";
                    if(generated_rules.indexOf(rule)==-1){
                        generated_rules.push(rule);
                        console.log(rule);
                    }
                }
            }
            elm.setAttribute('style', 'position:static !important');
            elm.style.removeProperty('top');
            //return;
        }else if(has_matched==0){
            if(elm.className){
                for (var j=0; j < class_list.length; j++){
                    rule="@@"+window.location.hostname+"##."+class_list[j];
                    if(generated_rules.indexOf(rule)==-1){
                        generated_rules.push(rule);
                        console.log(rule);
                    }
                }
            }
            //return;
        }else{
            //console.log("ignoring sticky: "+elm.id+","+elm.className+","+elm.tagName);
        }
        }
    }

    // Handle child elements
    for (node = elm.firstChild; node; node = node.nextSibling) {
        if (node.nodeType === 1) { // 1 == Element
            walk(node);
        }
    }
}

// Kick it off starting with the `body` element
c_walk(document.body,"onstart");

document.onchange = c_walk(document.body,"onchange");

document.onscroll = c_walk(document.body,"onscroll");

if(mutation_check){
    MutationObserver = window.MutationObserver || window.WebKitMutationObserver;

    // define a new observer
    var obs = new MutationObserver(function(mutations, observer) {
        // look through all mutations that just occured
        for(var i=0; i<mutations.length; ++i) {
            for(var j=0; j<mutations[i].addedNodes.length; ++j) {
                //console.log(mutations[i].addedNodes[j]);
                c_walk(mutations[i].addedNodes[j],"onmutation");
            }
        }
    });

    // have the observer observe for changes in children
    obs.observe(document.body, {
        attributes : true,
        childList: true,
        subtree: false
    });
}
